name: Deployment on the server
#Trigger will work only when the code is pushed to the branch.
on:
 push:
  branches:
    - master

jobs:      
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
         # Step 2: Set up SSH
      - name: Set up SSH key for deployment
        run: |
         mkdir -p ~/.ssh  # Ensure the .ssh directory exists
         echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519  # Using the raw SSH private key
         chmod 600 ~/.ssh/id_ed25519  # Setting the correct permissions for the private key
         ssh-keyscan -H 69.48.206.67 >> ~/.ssh/known_hosts  # Adding the server to known_hosts

      - name: Deploy to server
        run: |
         ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 deployerdev@69.48.206.67 << 'EOF'
            cd /home/deployerdev/coding/projects/craftlore/craftlore-instance-1 && \
            export PATH=$PATH:/home/deployerdev/.nvm/versions/node/v22.11.0/bin && \
            git pull origin master && \
            npm ci && \
            npm install pm2 -g && \
            export DATABASE_URL=${{ secrets.DATABASE_URL }} && \
            export CLOUD_NAME=${{ secrets.CLOUD_NAME }} && \
            export CLOUD_KEY=${{ secrets.CLOUD_KEY }} && \
            export CLOUD_SECERT=${{ secrets.CLOUD_SECERT }} && \
            export NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }} && \
            npm run build || { echo "Build failed"; exit 1; } && \
            pm2 list && \
            pm2 restart craftlore-instance-1 || { echo "PM2 restart failed"; exit 1; } && \
            pm2 save || { echo "PM2 save failed"; exit 1; }
         EOF
