name: Deployment of craftlore on server 

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub hosted runner

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: SSH into VPS and deploy
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}  # VPS IP address
        username: ${{ secrets.VPS_USER }}  # VPS SSH username
        key: ${{ secrets.VPS_SSH_KEY }}  # SSH private key for authentication
        script: |
          source ~/.bashrc  # Load the environment variables from .bashrc

          # Export only the required environment variables for build
          export DATABASE_URL=${{ secrets.DATABASE_URL }}
          export CLOUD_NAME=${{ secrets.CLOUD_NAME }}
          export CLOUD_KEY=${{ secrets.CLOUD_KEY }}
          export CLOUD_SECERT=${{ secrets.CLOUD_SECERT }}
          export NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}

          cd ${{ secrets.VPS_PROJECT_PATH }}  # Navigate to the project directory 
          git pull origin master  # Pull the latest code from GitHub
          npm install  # Install dependencies
          npm run build  # Rebuild the project
          pm2 restart craftlore-instance-1  # Restart the PM2 process
