name: Deployment of craftlore on server 

on:
  push:
    branches:
      - master  # Trigger deployment on master branch push

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: SSH into VPS and deploy
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}  # VPS IP address
        username: ${{ secrets.VPS_USER }}  # VPS SSH username
        key: ${{ secrets.VPS_SSH_KEY }}  # SSH private key for authentication
        script: |

           # Confirmation Message
           echo "SSH connection Succesfull!"
           
           # Navigate to the project directory
           cd ${{ secrets.VPS_PROJECT_PATH }}

           # Making sure the source bashrc to access the environment variables
           source ~/.bashrc

           # Exporting the required environment variable for the build process
           export DATABASE_URL=${{ secrets.DATABASE_URL }}
           export CLOUD_NAME=${{ secrets.CLOUD_NAME }}
           export CLOUD_KEY=${{ secrets.CLOUD_KEY }}
           export CLOUD_SECERT=${{ secrets.CLOUD_SECERT }}
           export NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
           
           # Pulling up the latest changes
           git pull origin master  
           

           # Building the project
           npm run build

           # Pm2 restarting process
           pm2 restart craftlore-instance-1

           # Saving the process
           pm2 save  
